default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 25 } %>
  database: tree
  username: tree_db_user
# For details on connection pooling, see Rails configuration guide
#   http://guides.rubyonrails.org/configuring.html#database-pooling
#
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>
#
development:
  <<: *default
  host: localhost
  port: 11177
  password: password

test:
  <<: *default
  host: localhost
  port: 11188
  password: password

production:
  <<: *default
  host: <%= ENV.fetch('DB_HOST') { 'DB_HOST_UNSET' } %>
  port: <%= ENV.fetch('DB_PORT') { 'DB_PORT_UNSET' } %>
  username: <%= ENV.fetch('DB_USERNAME') { 'DB_USERNAME_UNSET' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'DB_PASS_UNSET' } %>
  sslmode: require
