Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 25

AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - config.ru
    - db/**/*
    - Gemfile

