Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 25

AllCops:
  Exclude:
#    - app/channels/application_cable/channel.rb
#    - app/channels/application_cable/connection.rb
#    - app/controllers/application_controller.rb
#    - app/helpers/application_helper.rb
#    - app/jobs/application_job.rb
#    - app/mailers/application_mailer.rb
#    - app/models/application_record.rb
    - bin/**/*
    - config/**/*
    - config.ru
    - db/**/*
    - Gemfile
#    - log/**/*
#    - node_modues/**/*
#    - Rakefile
#    - spec/rails_helper.rb
#    - storage/**/*
#    - tmp/**/*
#    - vendor/**/*
